### ISSUE TITLE
Question about connectivity

### ISSUE THREAD

**Issue by TheDevFreak** [Apfel/DSiRC#1]
Will this utilise WPA2 connections or not?

**Comment by Apfel** [comment]
Obviously, I will try to implement WPA2 connections, however, that would require to port the Wifi library used in [wifiboot](http://problemkaputt.de/wifiboot.htm) to be ported to ndswifi and/or libnds, which sadly has not happened yet. Also, neither WEP nor open Access Points worked for me yet.
